import {
  GraduationCap,
  Linkedin,
  Instagram,
  Calendar,
  Users,
  Mic,
  Lightbulb,
  Landmark,
  Handshake,
  Cpu,
  TrendingUp,
  Code,
  GitBranch,
  PlugZap,
  Bug,
  Box,
  Network,
  Wrench,
  BookOpen,
  Info,
  Award,
  ImageIcon,
  ArrowLeft,
  ExternalLink,
  Star,
  Maximize2,
  Eye,
  Globe,
  RadioTower,
  Lock,
  Flame,
  FileText,
  RefreshCw,
  Workflow,
  Database,
  Monitor,
  Terminal,
  Puzzle,
  LayoutDashboard,
  ShieldCheck,
  Droplets,
  FlaskConical,
  Thermometer,
  Sigma,
  Ticket,
  Store,
  CreditCard,
  QrCode,
  ChevronLeft,
  ChevronRight,
  X,
  Menu,
} from "lucide-react";

export const ICONS = {
  "graduation-cap": GraduationCap,
  linkedin: Linkedin,
  instagram: Instagram,
  calendar: Calendar,
  users: Users,
  mic: Mic,
  lightbulb: Lightbulb,
  landmark: Landmark,
  handshake: Handshake,
  cpu: Cpu,
  "trending-up": TrendingUp,
  code: Code,
  "git-branch": GitBranch,
  "plug-zap": PlugZap,
  bug: Bug,
  box: Box,
  network: Network,
  wrench: Wrench,
  "book-open": BookOpen,
  info: Info,
  award: Award,
  image: ImageIcon,
  "arrow-left": ArrowLeft,
  "external-link": ExternalLink,
  star: Star,
  expand: Maximize2,
  eye: Eye,
  globe: Globe,
  "radio-tower": RadioTower,
  lock: Lock,
  flame: Flame,
  "file-text": FileText,
  "refresh-cw": RefreshCw,
  workflow: Workflow,
  database: Database,
  monitor: Monitor,
  terminal: Terminal,
  puzzle: Puzzle,
  "layout-dashboard": LayoutDashboard,
  "shield-check": ShieldCheck,
  droplets: Droplets,
  "flask-conical": FlaskConical,
  thermometer: Thermometer,
  sigma: Sigma,
  ticket: Ticket,
  store: Store,
  "credit-card": CreditCard,
  "qr-code": QrCode,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  x: X,
  menu: Menu,
};

export function Icon({ name, className = "" }) {
  const Cmp = ICONS[name] ?? Info;
  return <Cmp className={className} strokeWidth={2} />;
}
